-- ============================================================
-- V1 — Schéma public — Tables globales — Version définitive
-- ============================================================

CREATE TABLE IF NOT EXISTS public._users (
    id uuid NOT NULL,
    created_on timestamp(6),
    deleted boolean DEFAULT false,
    deleted_at timestamp(6),
    last_update_on timestamp(6),
    status smallint NOT NULL DEFAULT 0,
    created_at date,
    email character varying(255) NOT NULL,
    firstname character varying(255) NOT NULL,
    full_profile boolean NOT NULL DEFAULT false,
    lastname character varying(255),
    password character varying(255) NOT NULL,
    profile_status character varying(255) NOT NULL,
    roles character varying(255) NOT NULL,
    CONSTRAINT users_pkey PRIMARY KEY (id),
    CONSTRAINT users_email_unique UNIQUE (email),
    CONSTRAINT users_profile_status_check CHECK (
        profile_status = ANY (ARRAY[
            'REGISTERED','EMAIL_VERIFIED','PROFILE_COMPLETED',
            'ACTIVE','SUSPENDED','PENDING'
        ])
    ),
    CONSTRAINT users_roles_check CHECK (
        roles = ANY (ARRAY['MONITOR','STUDENT'])
    )
);

CREATE TABLE IF NOT EXISTS public.platform_admin (
    id uuid NOT NULL,
    created_on timestamp(6),
    deleted boolean DEFAULT false,
    deleted_at timestamp(6),
    last_update_on timestamp(6),
    status smallint NOT NULL DEFAULT 0,
    admin_status character varying(255),
    created_at timestamp(6),
    email character varying(255) NOT NULL,
    enabled boolean NOT NULL DEFAULT false,
    last_login_at timestamp(6),
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone_number character varying(255),
    residence character varying(255) NOT NULL,
    role character varying(255),
    CONSTRAINT platform_admin_pkey PRIMARY KEY (id),
    CONSTRAINT platform_admin_email_unique UNIQUE (email),
    CONSTRAINT platform_admin_status_check CHECK (
        admin_status = ANY (ARRAY['ACTIVE','PENDING','SUSPENDED','DISABLED'])
    ),
    CONSTRAINT platform_admin_role_check CHECK (
        role = ANY (ARRAY['REVIEWER','ROOT','SUPER_ADMIN'])
    )
);

CREATE TABLE IF NOT EXISTS public.tenants (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        START WITH 1 INCREMENT BY 1
    ),
    active boolean NOT NULL DEFAULT false,
    code character varying(255) NOT NULL,
    CONSTRAINT tenants_pkey PRIMARY KEY (id),
    CONSTRAINT tenants_code_unique UNIQUE (code)
);

CREATE TABLE IF NOT EXISTS public.driving_school_registry (
    id uuid NOT NULL,
    created_on timestamp(6),
    deleted boolean DEFAULT false,
    deleted_at timestamp(6),
    last_update_on timestamp(6),
    status smallint NOT NULL DEFAULT 0,
    address character varying(255) NOT NULL,
    city character varying(255),
    country character varying(255),
    created_at date,
    description character varying(255),
    driving_school_status character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    schema_name character varying(255) NOT NULL,
    school_name character varying(255) NOT NULL,
    website_url character varying(255),
    whatsapp_number character varying(255),
    admin_id uuid NOT NULL,
    CONSTRAINT driving_school_registry_pkey PRIMARY KEY (id),
    CONSTRAINT driving_school_registry_schema_name_unique UNIQUE (schema_name),
    CONSTRAINT driving_school_registry_admin_unique UNIQUE (admin_id),
    CONSTRAINT driving_school_registry_school_name_unique UNIQUE (school_name),
    CONSTRAINT driving_school_registry_status_check CHECK (
        driving_school_status = ANY (ARRAY[
            'APPROVED','ACTIVE','PENDING','SUSPENDED','REJECTED'
        ])
    ),
    CONSTRAINT driving_school_registry_admin_fk
        FOREIGN KEY (admin_id) REFERENCES public._users(id)
);

CREATE TABLE IF NOT EXISTS public.driving_school (
    id uuid NOT NULL,
    created_on timestamp(6),
    deleted boolean DEFAULT false,
    deleted_at timestamp(6),
    last_update_on timestamp(6),
    status smallint NOT NULL DEFAULT 0,
    address character varying(255) NOT NULL,
    city character varying(255),
    country character varying(255),
    created_at date,
    description character varying(255),
    driving_school_status character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    name character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    website_url character varying(255),
    whatsapp_number character varying(255),
    user_id uuid,
    CONSTRAINT driving_school_pkey PRIMARY KEY (id),
    CONSTRAINT driving_school_status_check CHECK (
        driving_school_status = ANY (ARRAY[
            'APPROVED','ACTIVE','PENDING','SUSPENDED','REJECTED'
        ])
    ),
    CONSTRAINT driving_school_user_fk
        FOREIGN KEY (user_id) REFERENCES public._users(id)
);

CREATE TABLE IF NOT EXISTS public.monitors (
    id uuid NOT NULL,
    created_on timestamp(6),
    deleted boolean DEFAULT false,
    deleted_at timestamp(6),
    last_update_on timestamp(6),
    status smallint NOT NULL DEFAULT 0,
    date_of_birth timestamp(6) NOT NULL,
    gender character varying(255) NOT NULL,
    nationality character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    residence_city character varying(255) NOT NULL,
    driving_school_id uuid,
    user_id uuid,
    CONSTRAINT monitors_pkey PRIMARY KEY (id),
    CONSTRAINT monitors_gender_check CHECK (
        gender = ANY (ARRAY['MALE','FEMALE'])
    ),
    CONSTRAINT monitors_user_fk
        FOREIGN KEY (user_id) REFERENCES public._users(id)
);

CREATE TABLE IF NOT EXISTS public.students (
    id uuid NOT NULL,
    created_on timestamp(6),
    deleted boolean DEFAULT false,
    deleted_at timestamp(6),
    last_update_on timestamp(6),
    status smallint NOT NULL DEFAULT 0,
    cni_recto_url character varying(255),
    cni_verso_url character varying(255),
    date_of_birth timestamp(6) NOT NULL,
    gender character varying(255) NOT NULL,
    license_category character varying(255),
    nationality character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    residence_city character varying(255) NOT NULL,
    user_id uuid,
    CONSTRAINT students_pkey PRIMARY KEY (id),
    CONSTRAINT students_gender_check CHECK (
        gender = ANY (ARRAY['MALE','FEMALE'])
    ),
    CONSTRAINT students_license_category_check CHECK (
        license_category = ANY (ARRAY['A','B','C','D','E','G'])
    ),
    CONSTRAINT students_user_fk
        FOREIGN KEY (user_id) REFERENCES public._users(id)
);

CREATE TABLE IF NOT EXISTS public.school_join_request (
    id uuid NOT NULL,
    created_on timestamp(6),
    deleted boolean DEFAULT false,
    deleted_at timestamp(6),
    last_update_on timestamp(6),
    status smallint NOT NULL DEFAULT 0,
    driving_school_id uuid NOT NULL,
    join_status character varying(255) NOT NULL,
    requested_role character varying(255) NOT NULL,
    user_id uuid NOT NULL,
    CONSTRAINT school_join_request_pkey PRIMARY KEY (id),
    CONSTRAINT school_join_request_join_status_check CHECK (
        join_status = ANY (ARRAY['PENDING','APPROVED','REJECTED'])
    ),
    CONSTRAINT school_join_request_role_check CHECK (
        requested_role = ANY (ARRAY['MONITOR','STUDENT'])
    ),
    CONSTRAINT school_join_request_user_fk
        FOREIGN KEY (user_id) REFERENCES public._users(id),
    CONSTRAINT school_join_request_school_fk
        FOREIGN KEY (driving_school_id) REFERENCES public.driving_school(id)
);

CREATE TABLE IF NOT EXISTS public.email_verification_tokens (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    token character varying(255) NOT NULL,
    expires_at timestamp NOT NULL,
    used boolean NOT NULL DEFAULT false,
    created_at timestamp DEFAULT now(),
    CONSTRAINT email_verification_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT email_verification_tokens_token_unique UNIQUE (token),
    CONSTRAINT email_verification_tokens_user_fk
        FOREIGN KEY (user_id) REFERENCES public._users(id)
);

CREATE TABLE IF NOT EXISTS public.password_reset_tokens (
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    token character varying(255) NOT NULL,
    expires_at timestamp NOT NULL,
    used boolean NOT NULL DEFAULT false,
    created_at timestamp DEFAULT now(),
    CONSTRAINT password_reset_tokens_pkey PRIMARY KEY (id),
    CONSTRAINT password_reset_tokens_token_unique UNIQUE (token),
    CONSTRAINT password_reset_tokens_user_fk
        FOREIGN KEY (user_id) REFERENCES public._users(id)
);