-- ============================================================
-- V1 — Schéma public initial
-- Tables globales : users, admins, registry, tenants
-- ============================================================

-- Extension UUID si pas déjà présente
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

-- ─── USERS ───────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS _users (
    id uuid NOT NULL,
    created_on timestamp(6) without time zone,
    deleted boolean DEFAULT false,
    deleted_at timestamp(6) without time zone,
    last_update_on timestamp(6) without time zone,
    status smallint NOT NULL,
    created_at date,
    email character varying(255) NOT NULL,
    firstname character varying(255) NOT NULL,
    full_profile boolean NOT NULL,
    lastname character varying(255),
    password character varying(255) NOT NULL,
    profile_status character varying(255) NOT NULL,
    roles character varying(255) NOT NULL,
    CONSTRAINT _users_pkey PRIMARY KEY (id),
    CONSTRAINT ukhchfjvwnaa27i27bfwv0y6n1x UNIQUE (email),
    CONSTRAINT _users_profile_status_check CHECK (
        profile_status = ANY (ARRAY[
            'REGISTERED', 'EMAIL_VERIFIED', 'PROFILE_COMPLETED',
            'ACTIVE', 'SUSPENDED', 'PENDING'
        ])
    ),
    CONSTRAINT _users_roles_check CHECK (
        roles = ANY (ARRAY['MONITOR', 'STUDENT'])
    )
);

-- ─── PLATFORM ADMIN ──────────────────────────────────────────
CREATE TABLE IF NOT EXISTS plateform_admin (
    id uuid NOT NULL,
    created_on timestamp(6) without time zone,
    deleted boolean DEFAULT false,
    deleted_at timestamp(6) without time zone,
    last_update_on timestamp(6) without time zone,
    status smallint NOT NULL,
    admin_status character varying(255),
    created_at timestamp(6) without time zone,
    email character varying(255) NOT NULL,
    enabled boolean NOT NULL,
    last_login_at timestamp(6) without time zone,
    name character varying(255) NOT NULL,
    password character varying(255) NOT NULL,
    phone_number character varying(255),
    residence character varying(255) NOT NULL,
    role character varying(255),
    CONSTRAINT plateform_admin_pkey PRIMARY KEY (id),
    CONSTRAINT uk36bpyfrxqirewg61hr9wytf1u UNIQUE (email),
    CONSTRAINT plateform_admin_admin_status_check CHECK (
        admin_status = ANY (ARRAY['ACTIVE', 'PENDING', 'SUSPENDED', 'DISABLED'])
    ),
    CONSTRAINT plateform_admin_role_check CHECK (
        role = ANY (ARRAY['REVIEWER', 'ROOT', 'SUPER_ADMIN'])
    )
);

-- ─── TENANTS ─────────────────────────────────────────────────
CREATE TABLE IF NOT EXISTS tenants (
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY (
        START WITH 1 INCREMENT BY 1
    ),
    active boolean NOT NULL,
    code character varying(255) NOT NULL,
    CONSTRAINT tenants_pkey PRIMARY KEY (id),
    CONSTRAINT ukaye4nalvpsbxpjq0vt2ulaiqi UNIQUE (code)
);

-- ─── DRIVING SCHOOL REGISTRY ─────────────────────────────────
-- Table globale : demandes de création d'auto-école (avant approbation)
CREATE TABLE IF NOT EXISTS driving_school_registry (
    id uuid NOT NULL,
    created_on timestamp(6) without time zone,
    deleted boolean DEFAULT false,
    deleted_at timestamp(6) without time zone,
    last_update_on timestamp(6) without time zone,
    status smallint NOT NULL,
    address character varying(255) NOT NULL,
    city character varying(255),
    country character varying(255),
    created_at date,
    description character varying(255),
    driving_school_status character varying(255) NOT NULL,
    email character varying(255) NOT NULL,
    phone_number character varying(255) NOT NULL,
    schema_name character varying(255) NOT NULL,
    school_name character varying(255) NOT NULL,
    website_url character varying(255),
    whatsapp_number character varying(255),
    admin_id uuid NOT NULL,
    CONSTRAINT driving_school_registry_pkey PRIMARY KEY (id),
    CONSTRAINT uk5m6iu0dpwylvcyqukidk5hev5 UNIQUE (schema_name),
    CONSTRAINT ukaum59f9r0xhpmqkejd0jr41k8 UNIQUE (admin_id),
    CONSTRAINT ukse6cecw95y3qaybw9tl5wnmq3 UNIQUE (school_name),
    CONSTRAINT driving_school_registry_driving_school_status_check CHECK (
        driving_school_status = ANY (ARRAY[
            'APPROVED', 'ACTIVE', 'PENDING', 'SUSPENDED', 'REJECTED'
        ])
    ),
    CONSTRAINT fk9jul6lslua9t9nygmpydsbds1
        FOREIGN KEY (admin_id) REFERENCES _users(id)
);