spring:
  config:
    import: optional:file:.env[.properties]
  application:
    name: driveHub
  datasource:
    url: jdbc:postgresql://localhost:5432/${DBNAME}
    username: postgres
    password: root
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        multiTenancy: SCHEMA
        dialect: org.hibernate.dialect.PostgreSQLDialect
  devtools:
    restart:
      enabled: false

server:
  port: 8082

cors:
  allowed-origins: "*"
  allowed-methods: "*"
  allowed-headers: "*"
  exposed-headers: "*"
  allow-credentials: true
  max-age: 3600

logging:
  level:
    org.springframework.security: DEBUG
    org.springdoc: DEBUG
    org.springframework.web: DEBUG
jwt:
  secret: ${JWT_SECRET_KEY}
app:
  root-admin:
    email: root@gmail.com
    password: root@admin123
  dbname: ${DBNAME}